export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const RAGISTRATION_ROUTE = '/ragistration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'